apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: go-demo-2  
spec:
  replicas: 2
  selector:
    matchLabels:
      type: backend
      service: go-demo-2  # They must match the labels defined in the spec.template
  template:
    metadata:
      labels:
        type: backend
        service: go-demo-2
        db: mongo
        language: go
    spec:  # If the containers are not running, it will use this info to start them
      containers:
      - name: db
        image: mongo:3.3
      - name: api
        image: vfarcic/go-demo-2
        env:
        - name: DB
          value: localhost